---
- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Install libnginx-mod-stream
  ansible.builtin.package:
    name: libnginx-mod-stream
    state: present

- name: Check ngx_stream_module.so exists
  stat:
    path: "{{ nginx_modules_path }}ngx_stream_module.so"
  register: file_info

- name: Check ngx_stream_module.so exists
  fail:
    msg: "ngx_stream_module.so is not found, stopping execution."
  when: not file_info.stat.exists

- name: Create /etc/nginx/nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_path }}"
    owner: "{{ cfg_owner }}"
    group: "{{ cfg_group }}"
    mode: '0644'
  notify: Restart Nginx